name: Build Development

jobs:
  # 1. Build apps only if no existing build found
  build_android_app:
    type: build
    params:
      platform: android
      profile: development

  build_ios_simulator_app:
    type: build
    params:
      platform: ios
      profile: development-simulator

  build_ios_app:
    type: build
    params:
      platform: ios
      profile: development

  # 3. Notify about failures
  notify_failures:
    after: [build_android_app, build_ios_simulator_app, build_ios_app]
    if: failure()
    steps:
      - run: |
          set -e
          MSG=""
          # Android failures
          if [[ "${AFTER_BUILD_ANDROID_APP_STATUS}" == "failure" ]]; then
            MSG+="*•* Android build step failed.\n"
          fi
          # iOS device failures
          if [[ "${AFTER_BUILD_IOS_APP_STATUS}" == "failure" ]]; then
            MSG+="*•* iOS build step failed.\n"
          fi
          # iOS simulator failures
          if [[ "${AFTER_BUILD_IOS_SIMULATOR_APP_STATUS}" == "failure" ]]; then
            MSG+="*•* iOS Simulator build step failed.\n"
          fi

          # Send Slack notification if there are any failures
          if [[ -n "$MSG" ]]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{
                \"username\": \"EAS - WORKFLOWS\",
                \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\",
                \"channel\": \"task-wan\",
                \"attachments\": [{
                  \"fallback\": \"🚨 Build Development Workflow Failed\",
                  \"pretext\": \"🚨 Build Development Workflow Failed: <https://expo.dev/accounts/nyplex-studio/projects/task-wan/workflows|Check workflows>\",
                  \"color\": \"#D00000\",
                  \"fields\": [{
                    \"title\": \"Details\",
                    \"value\": \"$MSG\",
                    \"short\": false
                  }]
                }]
              }" \
              "$SLACK_WEBHOOK_URL"
          fi
    env:
      AFTER_BUILD_ANDROID_APP_STATUS: ${{ after.build_android_app.status }}
      AFTER_BUILD_IOS_SIMULATOR_APP_STATUS: ${{ after.build_ios_simulator_app.status }}
      AFTER_BUILD_IOS_APP_STATUS: ${{ after.build_ios_app.status }}
