name: Publish Production
on:
  pull_request_labeled:
    labels: ["eas-production"]

jobs:
  # 1. Build Android and iOS apps for production
  build_android:
    type: build
    env:
      EXPO_PUBLIC_APP_VARIANT: "production"
    params:
      platform: android
      profile: production

  build_ios:
    type: build
    env:
      EXPO_PUBLIC_APP_VARIANT: "production"
    params:
      platform: ios
      profile: production

  # 2. Single notifier for all failures
  notify_failures:
    after: [build_android, build_ios]
    if: failure()
    steps:
      - run: |
          set -e
          MSG=""
          # Android build failures
          if [[ "${AFTER_BUILD_ANDROID_STATUS}" == "failure" ]]; then
            MSG+="*•* Android Production build step failed.\n"
          fi
          # iOS build failures
          if [[ "${AFTER_BUILD_IOS_STATUS}" == "failure" ]]; then
            MSG+="*•* iOS Production build step failed.\n"
          fi
          # Send consolidated Slack notification
          curl -X POST -H 'Content-type: application/json' \
            --data "{ \
              \"username\": \"EAS - WORKFLOWS\", \
              \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\", \
              \"channel\": \"task-wan\", \
              \"attachments\": [ \
                { \
                  \"fallback\": \"🚨 Publish Production Workflow Failed: <https://expo.dev/accounts/nyplex-studio/projects/task-wan/workflows|Check workflows>\", \
                  \"pretext\": \"🚨 Publish Production Workflow Failed: <https://expo.dev/accounts/nyplex-studio/projects/task-wan/workflows|Check workflows>\", \
                  \"color\": \"#D00000\", \
                  \"fields\": [ \
                    { \
                      \"title\": \"Details\", \
                      \"value\": \"$MSG\", \
                      \"short\": false \
                    } \
                  ] \
                } \
              ] \
            }" \
            "$SLACK_WEBHOOK_URL"
    env:
      AFTER_BUILD_ANDROID_STATUS: ${{ after.build_android.status }}
      AFTER_BUILD_IOS_STATUS: ${{ after.build_ios.status }}

  # 3. Notify Slack about Android build success
  notify_android_results:
    after: [build_android]
    if: success()
    steps:
      - run: |
          set -e
          MSG=""
          # 1) Did we ever run get/build/update for Android?
          if [[ "${AFTER_BUILD_ANDROID_STATUS}" == "success" ]]; then
            MSG+="✅ New Android PRODUCTION build created.\n"
          fi
          # 2) Any Android failures? (notify.Failures already runs, so skip here)
          # Send only if we got *some* positive result
          if [[ -n "$MSG" ]]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$MSG\", \"username\": \"EAS - WORKFLOWS\", \
              \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\", \
              \"channel\":\"task-wan\"}" \
              "$SLACK_WEBHOOK_URL"
          fi
    env:
      AFTER_BUILD_ANDROID_STATUS: ${{ after.build_android.status }}

  # 4. Notify Slack about iOS build success
  notify_ios_results:
    after: [build_ios]
    if: success()
    steps:
      - run: |
          set -e
          MSG=""
          if [[ "${AFTER_BUILD_IOS_STATUS}" == "success" ]]; then
            MSG+="✅ New iOS PRODUCTION build created.\n"
          fi
          if [[ -n "$MSG" ]]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$MSG\", \"username\": \"EAS - WORKFLOWS\", \
              \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\", \
              \"channel\":\"task-wan\"}" \
              "$SLACK_WEBHOOK_URL"
          fi
    env:
      AFTER_BUILD_IOS_STATUS: ${{ after.build_ios.status }}

  # 5. Submit Android to Play Store
  submit_android_build:
    name: Submit Android Build
    needs: [build_android]
    type: submit
    params:
      profile: production
      build_id: ${{ needs.build_android.outputs.build_id }}

  # 6. Notify Slack about Android submission
  notify_android_submission:
    after: [submit_android_build]
    if: success()
    steps:
      - run: |
          set -e
          MSG=""
          # 1) Did we ever run get/build/update for Android?
          if [[ "${AFTER_SUBMIT_ANDROID_STATUS}" == "success" ]]; then
            MSG+=":rocket: Android build submitted to the Play Store.\n"
          fi
          # 2) Any Android failures? (notify.Failures already runs, so skip here)
          # Send only if we got *some* positive result
          if [[ -n "$MSG" ]]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$MSG\", \"username\": \"EAS - WORKFLOWS\", \
              \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\", \
              \"channel\":\"task-wan\"}" \
              "$SLACK_WEBHOOK_URL"
          fi
    env:
      AFTER_SUBMIT_ANDROID_STATUS: ${{ after.submit_android_build.status }}

  # 7. Submit iOS to App Store
  submit_ios_build:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      profile: production
      build_id: ${{ needs.build_ios.outputs.build_id }}

  # 8. Notify Slack about iOS submission
  notify_ios_submission:
    after: [submit_ios_build]
    if: success()
    steps:
      - run: |
          set -e
          MSG=""
          # 1) Did we ever run get/build/update for iOS?
          if [[ "${AFTER_SUBMIT_IOS_STATUS}" == "success" ]]; then
            MSG+=":rocket: iOS build submitted to the App Store.\n"
          fi
          # 2) Any iOS failures? (notify.Failures already runs, so skip here)
          # Send only if we got *some* positive result
          if [[ -n "$MSG" ]]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$MSG\", \"username\": \"EAS - WORKFLOWS\", \
              \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\", \
              \"channel\":\"task-wan\"}" \
              "$SLACK_WEBHOOK_URL"
          fi
    env:
      AFTER_SUBMIT_IOS_STATUS: ${{ after.submit_ios_build.status }}

  # 9. Extract PR info and notify Jira
  notify_jira:
    after: [submit_android_build, submit_ios_build]
    env:
      AFTER_SUBMIT_ANDROID_STATUS: ${{ after.submit_android_build.status }}
      AFTER_SUBMIT_IOS_STATUS: ${{ after.submit_ios_build.status }}
    if: |
      after.submit_android_build.status == 'success' && after.submit_ios_build.status == 'success'
    steps:
      - run: |
          echo "Extracting PR info..."
          echo "$GITHUB_TOKEN"
          set -e

          BRANCH="${{ github.ref_name }}"
          # encode branch if it may contain slashes
          BRANCH_ENC=$(jq -nr --arg v "$BRANCH" '$v|@uri')

          PRS_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/nyplex/task-wan/pulls?head=nyplex:${BRANCH_ENC}&state=open")

          # Safely extract title and PR number when response is an array with at least one element
          PR_TITLE=$(echo "$PRS_JSON" | jq -r 'if type=="array" and length>0 then .[0].title else "" end')
          PR_NUMBER=$(echo "$PRS_JSON" | jq -r 'if type=="array" and length>0 then .[0].number else "" end')

          if [ -z "$PR_TITLE" ] || [ -z "$PR_NUMBER" ]; then
            echo "No open PR found for branch $BRANCH"
            echo "API response (debug): $PRS_JSON"
            exit 1
          fi

          echo "PR Title: $PR_TITLE"
          echo "PR Number: $PR_NUMBER"

          # Extract Jira key from PR title
          PR_JIRA_KEY=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+' | head -1 || true)
          echo "Jira Key from PR title: ${PR_JIRA_KEY:-'None found'}"

          # Get all commits in the PR
          echo "Fetching commits for PR #$PR_NUMBER..."
          COMMITS_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/nyplex/task-wan/pulls/$PR_NUMBER/commits")
          echo "Commits JSON: $COMMITS_JSON"

          # Extract all commit messages and find Jira keys
          echo "Extracting Jira keys from commit messages..."
          COMMIT_JIRA_KEYS=$(echo "$COMMITS_JSON" | jq -r '.[].commit.message' | grep -oE '[A-Z]+-[0-9]+' | sort -u || true)
          echo "Commit Jira keys: $COMMIT_JIRA_KEYS"

          # Combine all Jira keys (PR title + commits) and remove duplicates
          echo "Combining all Jira keys (PR title + commits) and removing duplicates..."
          ALL_JIRA_KEYS=""
          if [ ! -z "$PR_JIRA_KEY" ]; then
            ALL_JIRA_KEYS="$PR_JIRA_KEY"
          fi
          if [ ! -z "$COMMIT_JIRA_KEYS" ]; then
            if [ ! -z "$ALL_JIRA_KEYS" ]; then
              ALL_JIRA_KEYS="$ALL_JIRA_KEYS"$'\n'"$COMMIT_JIRA_KEYS"
            else
              ALL_JIRA_KEYS="$COMMIT_JIRA_KEYS"
            fi
          fi
          echo "All Jira keys combined: $ALL_JIRA_KEYS"

          # Remove duplicates and create final array
          echo "Removing duplicates and creating final array..."
          UNIQUE_JIRA_KEYS=$(echo "$ALL_JIRA_KEYS" | sort -u | grep -v '^$' || true)

          if [ -z "$UNIQUE_JIRA_KEYS" ]; then
            echo "No Jira keys found in PR title or commit messages"
          else
            echo "Found Jira keys:"
            echo "$UNIQUE_JIRA_KEYS"
            
            # Convert to JSON array format for the webhook
            echo "Converting Jira keys to JSON array format..."
            JIRA_KEYS_JSON=$(echo "$UNIQUE_JIRA_KEYS" | jq -R -s 'split("\n") | map(select(length > 0))')
            echo "Jira keys JSON: $JIRA_KEYS_JSON"
            
            echo "Calling Jira webhook with keys: $JIRA_KEYS_JSON"

            curl -X POST -H 'Content-type: application/json' \
              -H "X-Automation-Webhook-Token: $JIRA_WEBHOOK_TOKEN_RELEASE_READY" \
              --data "{\"issues\":$JIRA_KEYS_JSON}" \
              https://api-private.atlassian.com/automation/webhooks/jira/a/aee1c92e-a7f0-4e88-a3ba-77a03f97ee84/01989183-e12f-7d6f-9de7-f0b021fc0c42
          fi

  # 10. Notify Slack if Jira failed
  notify_jira_failure:
    after: [notify_jira]
    if: failure()
    steps:
      - run: |
          set -e
          MSG="🚨 Failed to notify Jira! Check the logs in the workflow publish-production to get the Jira keys impacted.\n"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\", \"username\": \"EAS - WORKFLOWS\", \
            \"icon_url\": \"https://raw.githubusercontent.com/nyplex/bot-icons/main/expo-icon.png\", \
            \"channel\":\"task-wan\"}" \
            "$SLACK_WEBHOOK_URL"
          fi
