name: Deploy to Preview

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment (preview)
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: preview
        # more steps below where you run your deployment scripts inside the same action

