name: Require PR Label
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for at least one label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            if (!labels || labels.length === 0) {
              core.setFailed("❌ This PR must have at least one label before merging.");
            } else {
              console.log(`✅ Found labels: ${labels.map(l => l.name).join(", ")}`);
            }
